### ISSUE TITLE
Subscriptions with Redis

### ISSUE THREAD

**Issue by perrosnk** [srtucker22/chatty#22]
Hello and thank you for this wonderful and really helpful tutorial!

I was reading that the `PubSub` mechanism `graphql-subscriptions` are not suitable for production use.
Have you tried using `graphql-redis-subscriptions` or maybe do you have any code that you could share? That would be really helpful because I am facing some difficulties there.

Thank you once again

**Comment by srtucker22** [comment]
`graphql-redis-subscriptions` is an excellent package, and a near perfect replacement for `graphql-subscriptions` without much additional code.

```js
// old
// import { PubSub } from 'graphql-subscriptions';
// export const pubsub = new PubSub();

// new
import { RedisPubSub } from 'graphql-redis-subscriptions';
export const pubsub = new RedisPubSub();
```

The only major change to the code (which is also a major performance enhancement), is to make topics more discrete.

Right now when a new `Message` gets created, we call the `messageAdded` subscription like this:
```js
const MESSAGE_ADDED_TOPIC = 'messageAdded';

// when a message is created we call this
pubsub.publish(MESSAGE_ADDED_TOPIC, { [MESSAGE_ADDED_TOPIC]: message });

...
// our subscription resolver looks like this
Subscription: {
    messageAdded: {
      subscribe: withFilter(
        () => pubsub.asyncIterator(MESSAGE_ADDED_TOPIC), // super inefficient
        (payload, args, ctx) => {
          return ctx.user.then((user) => {
            return Boolean(
              args.groupIds &&
              ~args.groupIds.indexOf(payload.messageAdded.groupId) &&
              user.id !== payload.messageAdded.userId, // don't send to user creating message
            );
          });
        },
      ),
    },

... 
```
The issue with this setup is our filter in `withFilter` will be called every time a message gets published and will run against every single subscriber to `MESSAGE_ADDED_TOPIC`, which is every single active user in the app!

Instead we can make the topic specific to the group where the message is being added:
```js
// this topic will look like 'messageAdded.1' for group with id = 1
pubsub.publish(`${MESSAGE_ADDED_TOPIC}.${message.groupId}`, { [MESSAGE_ADDED_TOPIC]: message });

...
// our subscription resolver now looks something like this
Subscription: {
    messageAdded: {
      subscribe: withFilter(
        (_, args) => pubsub.asyncIterator(`${MESSAGE_ADDED_TOPIC}.${args.groupId}`), // way more efficient
        (payload, args, ctx) => {
          return ctx.user.then((user) => {
            return Boolean(
              user.id !== payload.messageAdded.userId, // don't send to user creating message
            );
          });
        },
      ),
    },
... 
```
The first function passed to `withFilter` now establishes that only subscribers to a specific group's messages will get passed through the filter and notified of the new message.

This is untested code, but hopefully the concept is clear.

Let me know if this is helpful!

**Comment by perrosnk** [comment]
That was indeed really helpful. Thank you @srtucker22
