### ISSUE TITLE
Tutorial upgraded to tortilla@0.0.1-alpha.34

### ISSUE THREAD

**Issue by DAB0mB** [srtucker22/chatty#28]
@srtucker22 Great Work! Loved your tutorial. I've upgraded your tutorial to the latest version of Tortilla at https://github.com/DAB0mB/chatty; would you mind force pushing all refs (branches and tags) into your repo? I'm one of the main contributors of the Tortilla project together with @Urigo and we thought that it would be a good idea to test some new features of Tortilla like releases git-diffing and JSON file dumping. We can test these features with my fork however we would very much prefer that the changes would be part of the official repo. Thanks a lot!

**Comment by srtucker22** [comment]
Sweet! I'll give it a look this weekend

**Comment by srtucker22** [comment]
Hey @DAB0mB,

I upgraded to `tortiall@0.0.1-alpha.34` tried to replicate what you did in your fork (just to play around). 

Steps I took:
1. hard reset `master` to `v1` branch and `tortilla release bump major -m 'v1'`
2. hard reset `master` to `origin/master` branch and `tortilla release bump major -m 'v2'`
3. Force pushed all branches and tags

LMK if there's something I missed here. I appreciate you taking the time to save me the trouble of doing all that on my own, but I was curious to try out the tortilla release feature 😄 

Also, would be interested to try out the next steps ala git-diffing and JSON file dumping, and would appreciate any guidance you're able to provide!

**Comment by DAB0mB** [comment]
@srtucker22 It seems you did anything right with the release! Shouldn't have been complicated. In order to create a dump file you can simply write the following in the command line:

    $ tortilla dump create [optional out path]

The reason why this command was created is because we wanna have our own tutorial-base where tutorials are being generated with some additional features which are Tortilla specific using the dump file, like releases comparing. We would also like to use your tutorial for that purpose because it's well written and it uses a very popular framework in the JS echo system - React Native. Would that be OK?

**Comment by srtucker22** [comment]
of course! looking forward to the release!
