### ISSUE TITLE
undefined is not an object (evaluating 'action.payload.auth')

### ISSUE THREAD

**Issue by thienpow** [srtucker22/chatty#29]
followed the readme to setup.
server is able to start.
RN app crashed with this error
undefined is not an object (evaluating 'action.payload.auth')

**Comment by srtucker22** [comment]
thanks for the heads up!

i think just a simple extra guard should do the trick: 
`if(!action.payload || !action.payload.auth || !action.payload.auth.jwt)`

i've updated `master` with the fix

**Comment by thienpow** [comment]
thanks, it works.
